name: ci
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run Matrix Jobs
      run: |
        for version in 16.x 18.x 20.x 21.x; do
          echo "Running tests for Node.js $version"
          nvm use $version

          npm install
          npx eslint ShopifyGraphQL.js
          npx mocha
        done
    env:
      SHOP_MYSHOPIFY_DOMAIN: ${{ secrets.SHOP_MYSHOPIFY_DOMAIN }}
      SHOP_API_KEY: ${{ secrets.SHOP_API_KEY }}
