name: ci
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Lint code
      run: npx eslint ShopifyGraphQL.js
    - run: npx mocha
      env:
        SHOP_MYSHOPIFY_DOMAIN: ${{ secrets.SHOP_MYSHOPIFY_DOMAIN }}
        SHOP_API_KEY: ${{ secrets.SHOP_API_KEY }}